### ISSUE TITLE
Could you please tell me how to correct this error？Thank you in advance!!!

### ISSUE THREAD

**Issue by Starboy-at-earth** [aliyun/conditional-lane-detection#12]
~/projects/condlanenet/conditional-lane-detection$ python tools/condlanenet/culane/test_culane.py
Traceback (most recent call last):
  File "tools/condlanenet/culane/test_culane.py", line 21, in <module>
    from mmdet.models.detectors.condlanenet import CondLanePostProcessor
  File "/home/yjx/projects/condlanenet/conditional-lane-detection/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/yjx/projects/condlanenet/conditional-lane-detection/mmdet/models/backbones/__init__.py", line 1, in <module>
    from .hrnet import HRNet
  File "/home/yjx/projects/condlanenet/conditional-lane-detection/mmdet/models/backbones/hrnet.py", line 7, in <module>
    from mmdet.utils import get_root_logger
ImportError: cannot import name 'get_root_logger' from 'mmdet.utils' (/home/yjx/projects/condlanenet/conditional-lane-detection/mmdet/utils/__init__.py)

**Comment by Starboy-at-earth** [comment]
And this....
###############################################
Traceback (most recent call last):
  File "tools/condlanenet/culane/test_culane.py", line 20, in <module>
    from mmdet.utils.general_utils import mkdir
ModuleNotFoundError: No module named 'mmdet.utils.general_utils'

**Comment by Starboy-at-earth** [comment]
Anyone with the same puzzle is welcome......

**Comment by hustllz** [comment]
The installation of mmdetection should be based on this repo since we have added some files
. The "Install.md" has been updated to avoid misunderstanding.
 You can reinstall this framework as following:

git clone https://github.com/aliyun/conditional-lane-detection.git
cd conditional-lane-detection
pip install -r requirements/build.txt
python setup.py develop

**Comment by Starboy-at-earth** [comment]
python ./tools/condlanenet/culane/test_culane.py
/home/yjx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
The model and loaded state dict do not match exactly

unexpected key in source state_dict: bbox_head.reg_branch.0.conv.weight, bbox_head.reg_branch.0.bn.weight, bbox_head.reg_branch.0.bn.bias, bbox_head.reg_branch.0.bn.running_mean, bbox_head.reg_branch.0.bn.running_var, bbox_head.reg_branch.0.bn.num_batches_tracked, bbox_head.reg_branch.1.conv.weight, bbox_head.reg_branch.1.bn.weight, bbox_head.reg_branch.1.bn.bias, bbox_head.reg_branch.1.bn.running_mean, bbox_head.reg_branch.1.bn.running_var, bbox_head.reg_branch.1.bn.num_batches_tracked, bbox_head.reg_branch.2.conv.weight, bbox_head.reg_branch.2.bn.weight, bbox_head.reg_branch.2.bn.bias, bbox_head.reg_branch.2.bn.running_mean, bbox_head.reg_branch.2.bn.running_var, bbox_head.reg_branch.2.bn.num_batches_tracked

completed: 0, elapsed: 0sSegmentation fault (core dumped)

**Comment by Starboy-at-earth** [comment]
@hustllz emmmm, why does this error pop up? Do you have any idea?

**Comment by Starboy-at-earth** [comment]
Solved. Just need to rewrite ~ as the full path in config.py.

**Comment by HaoYongqiang1999** [comment]
> Solved. Just need to rewrite ~ as the full path in config.py.

Hello, I also encountered the same problem. Could you please tell me in detail how you solved it? thank you very much

**Comment by Starboy-at-earth** [comment]
@HaoYongqiang1999 
Which problem did you encounter?

**Comment by HaoYongqiang1999** [comment]
> @HaoYongqiang1999
> Which problem did you encounter?

Thanks to your previous comment,problem has been solved. Thank you!

**Comment by hilnkm** [comment]
Can you tell me How did you change it?

**Comment by Starboy-at-earth** [comment]
> Can you tell me How did you change it?

Could you please say chinese? I am a little confused about what you have asked. And I solved two problems in this round of discussion. Which one do you want to tackle? I will try my best to help you, in the way the author did to me.

**Comment by hilnkm** [comment]
> > Can you tell me How did you change it?
> 
> Could you please say chinese? I am a little confused about what you have asked. And I solved two problems in this round of discussion. Which one do you want to tackle? I will try my best to help you, in the way the author did to me.
您好，我想请问一下您上面出现的问题（core dumped）是怎么解决的？

**Comment by HaoYongqiang1999** [comment]
> > Can you tell me How did you change it?
> 
> Could you please say chinese? I am a little confused about what you have asked. And I solved two problems in this round of discussion. Which one do you want to tackle? I will try my best to help you, in the way the author did to me.

在您评论的帮助下，我的问题已经解决了，我现在没什么问题了。感谢！

**Comment by HaoYongqiang1999** [comment]
> > > Can you tell me How did you change it?
> > 
> > 
> > Could you please say chinese? I am a little confused about what you have asked. And I solved two problems in this round of discussion. Which one do you want to tackle? I will try my best to help you, in the way the author did to me.
> > 您好，我想请问一下您上面出现的问题（core dumped）是怎么解决的？

我是把"/conditional-lane-detection/configs/condlanenet/culane/culane_large_test.py"中的第六行改成了我自己的数据集路径，就没问题了。

**Comment by hilnkm** [comment]
> > > > Can you tell me How did you change it?
> > > 
> > > 
> > > Could you please say chinese? I am a little confused about what you have asked. And I solved two problems in this round of discussion. Which one do you want to tackle? I will try my best to help you, in the way the author did to me.
> > > 您好，我想请问一下您上面出现的问题（core dumped）是怎么解决的？
> 
> 我是把"/conditional-lane-detection/configs/condlanenet/culane/culane_large_test.py"中的第六行改成了我自己的数据集路径，就没问题了。

谢谢

**Comment by imadalishah** [comment]
Getting Error:

**/content/conditional-lane-detection
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "tools/condlanenet/tusimple/test_tusimple.py", line 19, in <module>
    from tools.condlanenet.common import tusimple_convert_formal, COLORS
ModuleNotFoundError: No module named 'tools'**

Any solution??
