### ISSUE TITLE
MMCV version

### ISSUE THREAD

**Issue by parthdave1210** [aliyun/conditional-lane-detection#3]
Hey! I tried to test on the tusimple large. I ran this code

python tools/condlanenet/tusimple/test_tusimple.py configs/condlanenet/tusimple/tusimple_large_test.py D:/conditional-lane-detection-master/tusimple_large.pth

and it gives error like this

File "tools/condlanenet/tusimple/test_tusimple.py", line 16, in <module>
    from mmdet.datasets import build_dataloader, build_dataset
  File "d:\conditional-lane-detection-master\mmdetection\mmdet\__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==0.5.6 is used but incompatible. Please install mmcv>=1.3.2, <=1.4.0.

What should I do?

**Comment by hustllz** [comment]
I guess you install the latest mmdetection? 
This repo is built on mmdetection v2.0, which uses a lower version of MMCV. You can try to install mmdetection framework from this repo and MMCV==0.5.6 is OK.
