### ISSUE TITLE
results do not agree with the author

### ISSUE THREAD

**Issue by CongerW** [aliyun/conditional-lane-detection#32]
I tested the model provided by the authors and the results were a bit different from what the authors described. 
Do you have the same experience?
model: large.
result:
[{"name":"Accuracy","value":0.9636818107904509,"order":"desc"},{"name":"FP","value":0.021141864366163457,"order":"asc"},{"name":"FN","value":0.03633477114785525,"order":"asc"},{"name":"F1","value":0.9712022686934042,"order":"asc"}]

**Comment by CongerW** [comment]
I know the reason:
I change the code here 
locations[:0, :, :] /= H 
locations[:1, :, :] /= W
to:
locations[:,0, :, :] /= H 
locations[:,1, :, :] /= W

**Comment by gautamjain1009** [comment]
@CongerW  Can you tell me how did you obtain those results! As per the documentation I can not figure it out how to obtain those metrics via the code available?

**Comment by CongerW** [comment]
> @CongerW Can you tell me how did you obtain those results! As per the documentation I can not figure it out how to obtain those metrics via the code available?

You can use the code: tools/condlanenet/tusimple/evaluate/lane.py to get the metrics.

**Comment by CongerW** [comment]
@gautamjain1009
