### ISSUE TITLE
mmdet这个目录是否需要删掉？？

### ISSUE THREAD

**Issue by SigmaLGX** [aliyun/conditional-lane-detection#4]
你好，我按照文档安装好环境之后，如果保留mmdet这个目录，则报“cannot import name 'deform_pool_ext'”
如果不保留Mmdel这个目录，则：'CurvelanesDataset is not in the dataset registry'

**Comment by WSTao** [comment]
不需要clone mmdetection，clone该工程后，在该工程root目录执行安装，具体命令看作者install文件

**Comment by Napier7** [comment]
你好，我也遇到了这个问题，请问是怎么解决的呢？

**Comment by Napier7** [comment]
> 你好，我也遇到了这个问题，请问是怎么解决的呢？

更新一下，我发现这个问题是由于运行setup.py时编译‘deform_pool_ext’失败导致的。降低setuptools版本可以解决该问题，我的最终版本如下：
`pip install setuptools==58.2.0`
