### ISSUE TITLE
export to onnx

### ISSUE THREAD

**Issue by lucky-xu-1994** [aliyun/conditional-lane-detection#5]
Hi, thank you for your great work! I have run it on my own datasets (different view with culane), and it predicts very well.
but I have problem in how to export .pth to onnx.

I have tried :
python  tools/pytorch2onnx.py  configs/condlanenet/culane/culane_small_test.py  ./culane_small.pth --out ./condlanenet.onnx --shape 320 800 
 
and it did save a ONNX file(44.7MB) in my path.
but when I open ONNX，I don't understand the output.
 
![image](https://user-images.githubusercontent.com/57120921/120775634-f8ae5a00-c555-11eb-820e-23f8817dc93c.png)

![image](https://user-images.githubusercontent.com/57120921/120775724-124fa180-c556-11eb-8c7c-860ab38a7c6e.png)

can anyone here help me out? thanks!

**Comment by hustllz** [comment]
We have not supported  exporting onnx in this repo. We did not adapt the newly added heads to the feature of exporting onnx of mmdetection. So the "pytorch2onnx.py" file in the official mmdetection does not work properly. It seems that only the backbone part is exported.
If you want to export onnx file, I suggest writing another script to extract the inference part of the model and geting out of this framework for now.

**Comment by lucky-xu-1994** [comment]
> We have not supported exporting onnx in this repo. We did not adapt the newly added heads to the feature of exporting onnx of mmdetection. So the "pytorch2onnx.py" file in the official mmdetection does not work properly. It seems that only the backbone part is exported.
> If you want to export onnx file, I suggest writing another script to extract the inference part of the model and geting out of this framework for now.

ok, I will try as you suggest. Thank you!

**Comment by jyang68sh** [comment]
@lucky-xu-1994 Hi, did you manage to get the script working? Thanks!

**Comment by lucky-xu-1994** [comment]
> @lucky-xu-1994 Hi, did you manage to get the script working? Thanks!

@jyang68sh sorry to be late. I have not.it's hard to export to ONNX for  existing conditional weight/bias and conditional branching in the network. for more you can refer to issue #13 .

**Comment by WYL-Projects** [comment]
@lucky-xu-1994 Hi, can ONNX be exported now?

**Comment by Jinming-Su** [comment]
@lucky-xu-1994 Hi, have you address this problem?

**Comment by HL-lucky** [comment]
> > 我们不支持在这笔回购协议中出口onnx。我们没有使新添加的头适应导出mmdetection的onnx功能。因此，官方mmdetection中的“pytorch2onnx.py”文件无法正常工作。似乎只出口了骨干部分。如果您想导出onnx文件，我建议编写另一个脚本来提取模型的推理部分，暂时退出此框架。>> 好的，我会按照你的建议试试。谢谢！嗨 ONNX可以导出了吗

**Comment by sjtuljw520** [comment]
> > We have not supported exporting onnx in this repo. We did not adapt the newly added heads to the feature of exporting onnx of mmdetection. So the "pytorch2onnx.py" file in the official mmdetection does not work properly. It seems that only the backbone part is exported.
> > If you want to export onnx file, I suggest writing another script to extract the inference part of the model and geting out of this framework for now.
> 
> ok, I will try as you suggest. Thank you!

@lucky-xu-1994 , Hi Xu, have you solved this problem and can you share your resolution? thank you.

**Comment by HL-lucky** [comment]
> > 我们不支持在这笔回购协议中出口onnx。我们没有使新添加的头适应导出mmdetection的onnx的功能。因此，官方mmdetection中的“pytorch2onnx.py”文件无法正常工作。似乎只出口了骨干部分。如果您想导出onnx文件，我建议编写另一个脚本来提取模型的推理部分，暂时退出此框架。
> 
> 好的，我会按照你的建议试试。谢谢！

嗨 解决这个问题了吗？ 你能分享一下你的解决方案吗？ 谢谢您！

**Comment by abhigoku10** [comment]
Has any one able to solve this export onnx issue @HL-lucky @lucky-xu-1994 @hustllz
