### ISSUE TITLE
Evaluation on CULane

### ISSUE THREAD

**Issue by ThomsonTang6** [aliyun/conditional-lane-detection#6]
hello! 
Could you please tell me how to calculate the f1 score on CULane dataset?
Thank you!

**Comment by cuichuan123456** [comment]
你可以参考SCNN怎么做的。

**Comment by FANG-MING** [comment]
> 你可以参考SCNN怎么做的。

python tools/condlanenet/culane/test_culane.py configs/condlanenet/culane/culane_medium_test.py work_dirs/exps/culane/medium/latest.pth
为什么得不到结果

**Comment by CongerW** [comment]
Hello, do you know how to calculate the F1-score now?

**Comment by alecapecchi** [comment]
@FANG-MING @CongerW I hope you solved your problem, else I managed to do it this way:
https://github.com/aliyun/conditional-lane-detection/issues/9#issuecomment-1236150771
