### ISSUE TITLE
Error was found in the test code of the CULane-medium.

### ISSUE THREAD

**Issue by sjg918** [aliyun/conditional-lane-detection#69]
You can fix the error simply by changing this one line: (config/condlanenet/culane/culane_medium_test.py)
205        data_list=data_root + '/list/test_debug_3000.txt',
->
205        data_list=data_root + '/list/test.txt',

Thank you for your insightful work!!!

**Comment by sjg918** [comment]
It took me an hour to find this error.
I left a comment for someone whose time is valuable....

**Comment by Pujin823** [comment]
> It took me an hour to find this error. I left a comment for someone whose time is valuable....
YOU SAVED MY DAY
