### ISSUE TITLE
Running inference

### ISSUE THREAD

**Issue by Tanay0101** [aliyun/conditional-lane-detection#8]
Hi, great work !! I am trying to run inference on some of my own images, but the output is incorrect. Here are the steps I followed:-

1. Loaded the small model trained on curvelanes dataset
2. Resized the image to (800,320)  [I want the output size to be (800,320) only].
3. Got the predictions 
4. Supplied the predictions to the appropriate post-processor with downscale = 8.
5. Supplied the output of the post-processor to adjust_results function with the following parameters
:- crop_shape = (320,800)
img_shape = (320,800)
crop_offset = (0,0)
ori_shape = (320,800)
6. The output I am getting is this - 
https://drive.google.com/file/d/1BwTaZ1I5VVWAEoQKjx2q6-Wg8UFzv6fT/view?usp=sharing

It would be great if you can tell me where I am going wrong.

Thank You

**Comment by Tanay0101** [comment]
The only way I was able to run it was by emulating the directory structure of one of the datasets. So if you want to run inference on a video, try to save it exactly like culane dataset.

1. Create a parent folder in the project directory named video_frames, containing 2 more folders of data and list. 
2. Extract all the frames from the video and save them in the data folder with one empty txt file for each image. So if your image is named 0032.jpg, the corresponding empty txt file will be 0032.lines.txt. Do this for every image.
3. Save the relative path from the video_frames folder for every image in a txt file named test.txt. So for the above image, the txt file will have the following line: "/data/0032.jpg"
4.Do this for every image that you want to run inference on. Create two empty txt files, train.txt and valid.txt.

Now edit the data root to point towards the video_frames folder. Run the model as given in the repo. Remember that these steps are for test_culane.py file. To test out tusimple simply swap out the model from culane_small.pth to tusimple_small.pth. I have tested it and it works.

**Comment by MeloHo** [comment]
Although this is closed, I did want to add more comments on how to run inference, which could be a reference for other people.
I tried out the tusimple model on my own data.
1. Create a folder to contain your own image data.
2. Put you images under that folder. Make sure your image size is (1280, 720)
3. Also create a json file (test_label.json). In that json file:
`
for img in imgs:
    obj = {"lanes": [], "h_samples": [], "raw_file": "path_to_img"}
    json.dump(obj, file_handle)
`
4. Follow the official instruction to modify the data path under config/.../
5. Add --show when running the inference to see the plotted images. Further modify the code to see the output values for each lane.

**Comment by MuftawoOmar** [comment]
> Although this is closed, I did want to add more comments on how to run inference, which could be a reference for other people. I tried out the tusimple model on my own data.
> 
> 1. Create a folder to contain your own image data.
> 2. Put you images under that folder. Make sure your image size is (1280, 720)
> 3. Also create a json file (test_label.json). In that json file:
>    `for img in imgs: obj = {"lanes": [], "h_samples": [], "raw_file": "path_to_img"} json.dump(obj, file_handle)`
> 4. Follow the official instruction to modify the data path under config/.../
> 5. Add --show when running the inference to see the plotted images. Further modify the code to see the output values for each lane.

hello @MeloHo , could you please clarify on point number 3, where should 
> `for img in imgs: obj = {"lanes": [], "h_samples": [], "raw_file": "path_to_img"} json.dump(obj, file_handle)`  be placed should be a new python script or should be added some where in the original code base

**Comment by lovelydjj** [comment]
> 嗨，伟大的工作！我正在尝试对我自己的一些图像运行推理，但输出不正确。以下是我遵循的步骤：-
> 
> 1. 加载了在曲线数据集上训练的小模型
> 2. 将图像大小调整为 （800，320） [我希望输出大小仅为 （800，320）]。
> 3. 得到预测
> 4. 将预测提供给相应的后处理器，降尺度 = 8。
> 5. 为adjust_results函数提供后处理器的输出，参数如下：- crop_shape = （320，800） img_shape = （320，800） crop_offset = （0，0） ori_shape = （320，800）
> 6. 我得到的输出是这样的 - https://drive.google.com/file/d/1BwTaZ1I5VVWAEoQKjx2q6-Wg8UFzv6fT/view?usp=sharing
> 
> 如果你能告诉我哪里出错了，那就太好了。
> 
> 谢谢
